notation improvement

diff --git a/opennic-up b/opennic-up
--- a/opennic-up
+++ b/opennic-up
@@ -52,7 +52,7 @@ done
 neededlist="awk sort curl fping drill"
 for needed in $neededlist; do
 	command -v "$needed" >/dev/null 2>&1 && continue
-	echo "$needed: is required but cannot be found in the environment path" 1>&2
+	echo "$needed: is required but cannot be found in the environment path" >&2
 	exit 1
 done
 
@@ -88,7 +88,7 @@ log "$apiurl"
 allhosts=$(curl --silent --connect-timeout 60 --resolve "$apihost:443:$apiip" "$apiurl")
 
 if [ -z "$allhosts" ]; then
-  echo 'API not available' 1>&2
+  echo 'API not available' >&2
   exit 1
 fi
 
@@ -158,10 +158,10 @@ if [ $reliablecount -ge 2 ]; then
       fi
     fi
   else
-    echo 'Not enough responsive OpenNIC servers available' 1>&2
+    echo 'Not enough responsive OpenNIC servers available' >&2
     exit 1
   fi
 else
-  echo 'Not enough OpenNIC servers available' 1>&2
+  echo 'Not enough OpenNIC servers available' >&2
   exit 1
 fi
